import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import user from '../img/user.png'
import setting from '../img/setting.png'
import buet_logo from '../img/buet_logo.png'
import buet_cover from '../img/Civil_Engineering_Building_of_BUET_seen_from_EME_Building.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navContainer}>
        <div className={styles.linkListLeft}>
          <ul className={styles.linkList}>
            <li className={styles.navLogo}>fighters<br />community</li>
          </ul>

        </div>
        <div className={styles.linkListMid}>
          <ul className={styles.linkList}>
            <li className={styles.listItem}>Road Map</li>
            <li className={styles.listItem}>Calender</li>
            <li className={styles.listItem}>engineering</li>
            <li className={styles.listItem}>medical</li>
          </ul>
        </div>
        <div className={styles.linkListRight}>
          <ul className={styles.linkList}>
            <li className={styles.listItemBtn}><Image height={18} width={18} src={user} alt='' ></Image></li>
            <li className={styles.listItemBtn}><Image height={18} width={18} src={setting} alt='' ></Image></li>
          </ul>

        </div>
      </nav>

      <main>
        <div className={styles.mainLeft}>
          <section>
            <p>Popular Threads</p>
            <hr />
            <div className={styles.shortcutContaner}>
              <Image src={buet_logo} width={42} height={42} alt='buet_fightersComm'></Image>
              <p>BUET</p>
            </div>
            <div className={styles.shortcutContaner}>
              <Image src={buet_logo} width={42} height={42} alt='buet_fightersComm'></Image>
              <p>BUET</p>
            </div>
            <div className={styles.shortcutContaner}>
              <Image src={buet_logo} width={42} height={42} alt='buet_fightersComm'></Image>
              <p>BUET</p>
            </div>
            <div className={styles.shortcutContaner}>
              <Image src={buet_logo} width={42} height={42} alt='buet_fightersComm'></Image>
              <p>BUET</p>
            </div>
          </section>
        </div>
        <div className={styles.mainRight}>
          <div className={styles.joiningCard}>
            <div className={styles.cardName}>
              <div className={styles.cardNameTop}>
                <Image src={buet_logo} width={32} height={32} alt='buet_fightersComm'></Image>
                <p>BUET - Bangladesh University Of Science and Technology</p>
                <p className={styles.uiTxt}>Last Activity 13min ago</p>
              </div>
              <div className={styles.cardNameAction}>
                <button className={styles.btnPrimary}>Join</button>
              </div>
              <div className={styles.cardMid}>
                <div className={styles.cardImageWrapper}>
                  <Image src={buet_cover} width={500} height={300} alt='buet_fightersComm'></Image>
                </div>
              </div>
              <div className={styles.cardFooter}>
                <p>399 Members</p>
                <p>49966 Msg</p>
                <p>39 News</p>
              </div>
            </div>
          </div>
          <div className={styles.joiningCard}>
            <div className={styles.cardName}>
              <div className={styles.cardNameTop}>
                <Image src={buet_logo} width={32} height={32} alt='buet_fightersComm'></Image>
                <p>BUET</p>
                <p className={styles.uiTxt}>Last Activity 13min ago</p>
              </div>
              <div className={styles.cardNameAction}>
                <button className={styles.btnPrimary}>Join</button>
              </div>
              <div className={styles.cardMid}>
                <div className={styles.cardImageWrapper}>
                  <Image src={buet_cover} width={500} height={300} alt='buet_fightersComm'></Image>
                </div>
              </div>
              <div className={styles.cardFooter}>
                <p>399 Members</p>
                <p>49966 Msg</p>
                <p>39 News</p>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
